### ISSUE TITLE
[FEATURE] Allow for dbl vanity urls to work when requesting for bots.

### ISSUE THREAD

**Issue by jpbberry** [dbl-marcorennmaus-de/issues#11]
**Feature description**: Like how https://top.gg/bot/shiro also allow dblstats.com/bot/shiro

**Why you feel it would be a good addition**: Being able to go straight to the page without copying ID's and stuff, shouldn't be too difficult either.

**Screenshots or Visual concept** (If applicable):

**Comment by Xignotic84** [comment]
This isn't possible since we aren't able to get vanity URL's from Top.gg's API. This would result in us scraping and isn't an efficient feature that we would like to implement.
