### ISSUE TITLE
[FEATURE] Ability to change between day and hourly graphs

### ISSUE THREAD

**Issue by jpbberry** [dbl-marcorennmaus-de/issues#16]
**Feature description**: Some sort of option which would let you turn the graphs to show hourly/daily information. Could default to daily and explicitly set the hourly if selected.

**Why you feel it would be a good addition**: This would heavily reduce graph lag if pin point accuracy is not needed, while also not removing the ability to have it.

**Screenshots or Visual concept** (If applicable):

**Comment by Luke-6723** [comment]
Elaborated more in #18
