### ISSUE TITLE
[BUG REPORT] Home page UI messed up

### ISSUE THREAD

**Issue by 3eif** [dbl-marcorennmaus-de/issues#17]
**Bug URL Origin**:
https://dblstatistics.com/
**Bug description**:
The text appears behind the background
**Reproduction Steps**:
Open https://dblstatistics.com/
**Expected Result**:
The title text appears in front of the background
**Actual Result**:
The title text appears behind the background
**Operating System**:
Windows 10
**Browser Version**:
Firefox (idk what version)
**Additional information / screenshots:**
![image](https://user-images.githubusercontent.com/29833473/96198190-f89b1480-0f08-11eb-9977-6570bb678d0a.png)

**Comment by Luke-6723** [comment]
This is a known bug, will be fixed in the next update

**Comment by Luke-6723** [comment]
Bug has since been fixed
