### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by timozaaijer** [dbl-marcorennmaus-de/issues#19]
**Bug URL Origin**: Webm not showing

**Bug description**: Images are not showing correctly

**Reproduction Steps**: Load page on Safari

**Expected Result**: Images should load normally

**Actual Result**: Images don't load normally

**Operating System**: MacOS

**Browser Version**: Latest¹

**Additional information / screenshots:**

¹Latest for 2012

**Comment by Luke-6723** [comment]
You're using a browser from 2012 an expecting it to work. Not LTS
