### ISSUE TITLE
Marco needs a Bodypillow

### ISSUE THREAD

**Issue by Timoaardappel** [dbl-marcorennmaus-de/issues#2]
Not sure what his tastes are but I think Asuna Yuuki from Sword Art Online or Chizuru Mizuhara from Rent a Girlfriend are perfect, they are also available for world-wide shipping so I don't see any issues there.

**Comment by Timoaardappel** [comment]
Sad

**Comment by Luke-6723** [comment]
Make a bug report 💢

**Comment by Timoaardappel** [comment]
You're a bug report

**Comment by QuantumCatYT** [comment]
probably catgirls
