### ISSUE TITLE
[BUG] Bot Page broken

### ISSUE THREAD

**Issue by ghost** [dbl-marcorennmaus-de/issues#21]
**Bug URL Origin**:
https://dblstatistics.com/bot/802603939194208258
https://dblstatistics.com

**Bug description**:
So that url seems to be down for some reason, also that bot is showing as "#" in top votes and server count

**Expected Result**:
It shouldn't be on the front page, obviously

**Actual Result**:
Well it shows in the front page!

**Operating System**:
Windows 10 20H2 (idk if you actually need this)

**Browser Version**:
Microsoft Edge | 88.0.705.68

**Additional information / screenshots:**
![image](https://user-images.githubusercontent.com/51095261/108101682-3d3de480-7090-11eb-8c25-5910d0723a5c.png)
![image](https://user-images.githubusercontent.com/51095261/108101690-416a0200-7090-11eb-9dcb-69930d50ca31.png)
![image](https://user-images.githubusercontent.com/51095261/108101742-52b30e80-7090-11eb-8998-f7be2f484ceb.png)

**Comment by ghost** [comment]
And that logo is copy of Zira lmao

**Comment by marcorennmaus** [comment]
Likely related to a rewrite of the fetcher that we've deployed earlier today, we'll take a look

**Comment by ghost** [comment]
Looks like you have fixed it, so i will close this issue.
