### ISSUE TITLE
[FEATURE] Server count rise past three days etc

### ISSUE THREAD

**Issue by promise** [dbl-marcorennmaus-de/issues#22]
**Feature description**:
See how much your bot has been added to other servers within a timeframe. Kind of like these (see screenshot), just as a graph instead and that we can maybe compare with other bots as well.
![image](https://user-images.githubusercontent.com/10573728/109969889-b8400580-7cf4-11eb-9c62-b746489fd8b3.png)

**Why you feel it would be a good addition**:
I feel like it would definitely be another way we could compare bots with each other and see who gains more servers than others.

**Comment by Luke-6723** [comment]
This is already a feature

**Comment by promise** [comment]
lol
