### ISSUE TITLE
[ADD]

### ISSUE THREAD

**Issue by juliuslov** [dbl-marcorennmaus-de/issues#23]
**Feature description**:
Add Bot Slash Command to Visual Code!

**Comment by Xignotic84** [comment]
Will be closing this as we are rebranding and rewriting the site, you can [read more here](https://docs.dblstatistics.com/blog/updates/the-future-dblstats) and if you would like to stay up to date you can join [our discord server](https://discord.com/invite/jjEauJXuZc)
