### ISSUE TITLE
[BUG] Gateway Timeout

### ISSUE THREAD

**Issue by Ameliaaaaaaa** [dbl-marcorennmaus-de/issues#24]
**Bug URL Origin**: https://dblstatistics.com/bot//* (Seems the home page works but is slowish)

**Bug description**: Website is offline a load of the time.

**Reproduction Steps**: Visit the website every so often

**Expected Result**: The website works.

**Actual Result**: CloudFlare Gateway Time-out

**Comment by marcorennmaus** [comment]
We're working on a solution for this, but due to the amount of data (and some technical difficulties along the way) it's taking a lot longer than we'd like. We'll update this issue once we have some new information.

**Comment by Ameliaaaaaaa** [comment]
Alright, pretty nice website tho
