### ISSUE TITLE
[BUG] “Broken” graph on mobile (iOS)

### ISSUE THREAD

**Issue by shi-gg** [dbl-marcorennmaus-de/issues#25]
**Bug URL Origin**:
https://dblstatistics.com/compare/857230367350063104/900353078128173097/

**Bug description**:
Always when I go to the page linked above on mobile (iOS/Safari) the graph only renders at the very right, it displays right on desktop.

**Reproduction Steps**:
Go to the link on mobile (iOS/Safari)

**Expected Result**:
Normal graph over the whole phone width

**Actual Result**:
Small graph

**Operating System**:
iOS 15.4 (iPhone 12)

**Browser Version**:
Safari

**Additional information / screenshots:**
![D20CF679-AF53-423F-9E3F-0D0BC97D7EF1](https://user-images.githubusercontent.com/71079641/161734759-9554670b-978d-49f2-8f7a-ea842251f857.png)

**Comment by Xignotic84** [comment]
Will be closing this as we are rebranding and rewriting the site, you can [read more here](https://docs.dblstatistics.com/blog/updates/the-future-dblstats) and if you would like to stay up to date you can join [our discord server](https://discord.com/invite/jjEauJXuZc)
