### ISSUE TITLE
[BUG] Data gaps occuring more often

### ISSUE THREAD

**Issue by th0mk** [dbl-marcorennmaus-de/issues#27]
**Bug URL Origin**:
https://dblstatistics.com/bot/356268235697553409
https://dblstatistics.com/bot/276060004262477825
https://dblstatistics.com/bot/720351927581278219

**Bug description**:
It seems like that in both the hourly and the daily list data gaps are starting to show up more often.

See an example of this below:

![image](https://github.com/dbl-statistics/issues/assets/9088316/99d3a72b-bd54-47d2-aada-32c786e39be0)

**Reproduction Steps**:
View one of the bots that do hourly updates, like the bots linked above

**Expected Result**:
The data is complete hour-by-hour and day-by-day

**Actual Result**:
The data has gaps, both in days and in hours.

**Comment by marcorennmaus** [comment]
Yep, we're aware
Top.gg's API has been massively unstable recently and whenever it's down the empty data appears

**Comment by th0mk** [comment]
Ah okay, I didn't know. Guess we'll have to wait for them to fix it, thanks
