### ISSUE TITLE
Time Frames for Graphs

### ISSUE THREAD

**Issue by 3eif** [dbl-marcorennmaus-de/issues#3]
**Feature description**:
Make it so that users can change the time frame for each graph.

- Include Time Frame Adverages at bottom of page also

**Why you feel it would be a good addition**:
Users will be able to focus on specific days and months.
**Screenshots or Visual concept** (If applicable):
![image](https://user-images.githubusercontent.com/29833473/89102572-8c0b8180-d3bf-11ea-932e-6a2c4891c6d3.png)

**Comment by Luke-6723** [comment]
More detailed in #18
