### ISSUE TITLE
[BUG] Vote table

### ISSUE THREAD

**Issue by nemoralis** [dbl-marcorennmaus-de/issues#7]
![marco is weeb](https://i.imgur.com/So187j5.png)
![marco needs a bodypillow](https://i.imgur.com/xQFEZT1.png)
I think this wasn't fully reset. Page: https://dblstatistics.com/bot/677951102913740801

**Comment by Luke-6723** [comment]
Will fix ASAP

**Comment by Luke-6723** [comment]
Issue has been fixed
